### ISSUE TITLE
I am curious to understand how you were able to solve this problem within the 3-second constraint, as that was one of the key requirements.

### ISSUE THREAD

**Issue by lakshman7781** [NandanaNandy/SIH-1652#5]
The problem statement involved the extraction and verification of information from semi-categorized data, such as educational certificates, marksheets, and other documents submitted by applicants for DRDO's Recruitment and Assessment Centre. From what I have done is utilized Azure Document Intelligence services for the OCR and structured text extraction, and then leveraged large language models (LLMs) for the verification against the applicant's biodata. You were able to achieve the required 3-second processing speed by optimizing your pipeline and leveraging the speed and accuracy of these AI technologies. I would really appreciate it if you could share more details on your specific approach, the tools and models you used, and any challenges you faced in meeting the performance requirements.

**Comment by NandanaNandy** [comment]
I have used the OCR named Surya which was developed for Indian languages by overcoming the disadvantages of EasyOCR as well as Tesseract OCR, and for the verification purpose the Google's Gemma model is used.
The model was directly used instead of any API calls since it was an Defence project.
I hope this would help you out!
